import Mainpost from "@/components/Mainpost";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";

import React from "react";
export async function getStaticPaths() {
	const res = await axios.get(`http://localhost:5000/api/v1/posts`);
	const paths = res.data.map((post) => {
		// const params = post._id
		return { params: { post: post._id } };
	});

	return { paths, fallback: false };
}
export async function getStaticProps({ params }) {
	const data = await axios(
		`http://localhost:5000/api/v1/posts/${params?.post}`
	);
	// const data = await res.json();
	const result = data.data;
	// console.log(data);

	return { props: { result } };
}
function post({ result }) {
	return (
		<>
			<Head>
				<title>BLOG</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<div>
				<Mainpost data={result} />
			</div>
		</>
	);
}

export default post;
