import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Postitem from "@/components/Postitem";
import axios from "axios";
import Head from "next/head";
import React from "react";

function Post({ posts }) {
	return (
		<>
			<Head>
				<title>My First App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<Navbar />

			<section className="  px-8 pt-20   ">
				<main className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 ">
					{posts.map((a) => (
						<Postitem
							data={a}
							key={a._id}
						/>
					))}
				</main>
			</section>
			<Footer />
		</>
	);
}

export default Post;
export async function getStaticProps() {
	// Call an external API endpoint to get posts.
	// You can use any data fetching library
	const res = await axios.get("http://localhost:5000/api/v1/posts");
	const posts = await res.data;

	// By returning { props: { posts } }, the Blog component
	// will receive `posts` as a prop at build time
	return {
		props: {
			posts,
		},
	};
}
